Remove extension in Rust
In MS Windows, `tempname()` generates a filename that conains `.` like
`IDA155.tmp`.  So the temp filename becomes like `IDA155.tmp.rs`
but rustc occurs an error:

error: invalid character `.` in crate name: `VIE8804.tmp`